# Generated by Django 4.2.1 on 2023-07-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0002_employer_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='created_by',
        ),
    ]
